[package]
name = "Pixelate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.6"
easy_paths = "0.1.1"
egui = "0.21.0"
eframe = "0.21.3"